---

partition_var_log: True
var_log_disk: /dev/vdb

base_pubkeys_enable: True
base_pubkeys_auth: username:password
base_pubkeys_host: key.example.tld
base_pubkeys_url: "https://{{ base_pubkeys_host }}"
base_addhost_url: "https://{{ base_pubkeys_host }}"

# On default we disable iptables but we want option to keep it on for customer-servers without external firewall
disable_iptables: True

# Default distribution CentOS 7
distro: "centos7"

wkv_site_env: default

sysctl_tcp_fin_timeout: 20

varnish_control_key: this-is-not-a-secure-key

timezone: Europe/Helsinki

# Install extra packages
#yum_extra_packages:
#  - packagename
