---
# defaults file for filebeat
filebeat_version: 6.x

# secrets should be managed to set these
# do not set and do not submit secret variables to git unencrypted
filebeat_kibana_host: "" 
filebeat_cloud_id: ""
filebeat_cloud_auth: ""

filebeat_logs:
  - /var/log/*.log
  - /var/log/secure
  - /var/log/maillog

# only errors and warnings logged from this log
messages_log: /var/log/messages

filebeat_log_mysql: false
filebeat_log_nginx: false
filebeat_log_php_fpm: false
filebeat_log_nginx_access: false

nginx_access_logs:
  - /var/log/nginx/http-*access.log
  - /var/log/nginx/ssl-*access.log

nginx_error_logs:
  - /var/log/nginx/http-*error.log
  - /var/log/nginx/ssl-*error.log

php_fpm_logs: 
  - /var/log/php-fpm/error.log