---
# defaults file for filebeat
filebeat:
  version: 6.x
  endpoint: logstash # lostash or escloud
  escloud:
    host: ""
    cloud_id: ""
    cloud_auth: ""
  logstash:
    endpoint: ""     # Hostname and IP e.g. my.logstash.server:12345, usually defined in secrets
    client_cert: ""
    client_key: ""
    ca_cert: ""
  # default groups of files to watch and rules for their (not)shipping
  log_files:
    - group: "secure"
      paths:
        - /var/log/secure
    - group: "messages"
      paths:
        - /var/log/messages
      # if include is defined, filebeat will ship only lines that match rules
      include:
        - '.*(?i)err.*' 
        - '.*(?i)warn.*'
    - group: "maillog"
      paths:   
        - /var/log/maillog
      include:
        - '.*(?i)err.*' 
        - '.*(?i)warn.*'
        - '.*(?i)bounce.*'
    - group: "monit"
      reqservice: "monit" 
      paths:   
        - /var/log/monit.log
      include: 
        - '.*(?i)error.*' 
    - group: "drupal"
      reqservice: "php-fpm"
      paths: 
      - /var/log/drupal.log
      exclude: 
        - '.*(?i)notice.*'
    - group: "php-fpm"
      reqservice: "php-fpm"
      paths: 
      - /var/log/php-fpm/*.log
      multiline:
        pattern: '^\[[0-9]{1,2}-[A-Z]{1}'
        negate: "true"
        match: "after"
      exclude: 
        - '.*(?i)notice.*'


# to add extra inputs, define filebeat.log_files_extra with same structure as filebeat.log_files
# or add
# filebeat.custom_inputs_block with syntax described in url 
# https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-log.html
# example -
# filebeat:
#   custom_inputs_block: | 
#         - type: log
#           paths:
#             - /my/custom/path/1
#             - /my/custom/path/2
#           include_lines: ['string1','string2']
#           exclude_lines: ['string1','string2']
#           fields:
#             log_type: syslog
#           fields_under_root: true
