---

# Setup all of our php-fpm related repositories.
- include: "repo.yml"

- include: "php56u.yml"
  when: php_package == "php56u"

- include: "php70u.yml"
  when: php_package == "php70u" or php_package == "php71u" or php_package == "php72u"

# Add db credentials as ENV for the php-fpm
- name: add db credentials to php_env_vars
  set_fact:
    php_env_vars: >
      {{ php_env_vars +
        [
          {
            "key": 'DB_NAME_' + item.name|upper,
            "value": item.name
          },
          {
            "key": 'DB_USER_' + item.name|upper,
            "value": item.user
          },
          {
            "key": 'DB_PASS_' + item.name|upper,
            "value": item.pass
          },
          {
            "key": 'DB_HOST_' + item.name|upper,
            "value": item.host|default('127.0.0.1')
          },
          {
            "key": 'DB_PORT_' + item.name|upper,
            "value": item.port|default('3306')
          }
        ]
      }}
  with_items:
    - "{{ databases }}"
  when: php_env_vars_include_db == True

- name: Add db credentials to environment variables
  blockinfile:
    path: /etc/environment
    block: |
      DB_NAME_{{ item.name|upper }}={{ item.name }}
      DB_USER_{{ item.name|upper }}={{ item.user }}
      DB_PASS_{{ item.name|upper }}={{ item.pass }}
      DB_HOST_{{ item.name|upper }}={{ item.host|default('127.0.0.1') }}
      DB_PORT_{{ item.name|upper }}={{ item.port|default('3306') }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name|upper }}-DB"
  with_items:
    - "{{ databases }}"
  backup: yes

- name: Add php_extra_env_vars
  set_fact:
    php_env_vars: >
      {{ php_env_vars + php_extra_env_vars }}
  when: php_extra_env_vars is defined

- name: Add varnish_control_key to env_vars
  set_fact:
    php_env_vars: >
      {{ php_env_vars +
        [
          {
            "key": 'VARNISH_CONTROL_KEY',
            "value": "{{ varnish_control_key }}"
          }
        ]
      }}
    when: varnish_control_key is defined

- yum:
    name={{ item }}
    state=present
  with_items:
    - MariaDB-client
    - gd
    - gd-devel
    - GraphicsMagick

# Delete legacy backups
# This is because we used to, but we really don't need to backup these.
- shell: find {{ item }} -regex '^.*@.*~$' -type f -delete
  with_items:
    - /etc/php-fpm.d
    - /etc/php.d

# PHP-FPM configurations
- template:
    src=www.conf.j2
    dest=/etc/php-fpm.d/www.conf
  when: php_package == "php56u"

- template:
    src=www.conf.php7.j2
    dest=/etc/php-fpm.d/www.conf
  when: php_package == "php70u" or php_package == "php71u" or php_package == "php72u"

- copy:
    src=php-fpm/{{ item }}
    dest=/etc/{{ item }}
  with_items:
    - php-fpm.conf

# PHP configuration ini file
- template:
    src=php.ini.j2
    dest={{ php_ini_file }}

- lineinfile:
    dest={{ php_ini_file }}
    regexp='^\[{{ item.section }}\]'
    state=present
    insertafter=EOF
    line='[{{ item.section }}]'
    create=True
    mode=644
  with_items:
    - "{{ php_ini }}"

# PHP configuration files
- ini_file: dest={{ php_ini_file }}
    section="{{ item.0.section }}"
    option="{{ item.1.key }}"
    value="{{ item.1.val }}"
  with_subelements:
    - "{{ php_ini }}"
    - options
  notify:
    - restart php-fpm

# Make papertrail follow appserver logs.
- lineinfile:
    dest=/etc/log_files.yml
    insertafter='files:'
    line='  - {{ item }}'
    mode=644
  with_items:
    - "{{ php_fpm_papertrail_follow }}"
  when:
    papertrail_enabled == True
  notify:
    - restart remote_syslog

# Make sure all services are ON and configured to start on boot
- service: name={{ item }} state=started enabled=yes
  with_items:
    - php-fpm
